# -*- coding: utf-8 -*-
"""Day-7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ucFN2m1xqUMsroCeDCaHD5is5OkqtZS
"""

#7.Write a Python script that:
#Use Genism to preprocess data from a sample text file, follow basic procedures like tokenization, stemming, lemmatization
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
def preprocess_text(text):
    return [
        lemmatizer.lemmatize(stemmer.stem(token), pos='v')
        for token in simple_preprocess(text)
        if token not in STOPWORDS
    ]
text = "Natural Language Processing is an amazing field. It is widely used in machine learning and AI projects."
processed_text = preprocess_text(text)
print("Processed Tokens:", processed_text)