# -*- coding: utf-8 -*-
"""Day-18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mU2jvS-9SJ9-Si_b5sQOTaLRoui4sWP6
"""

#Write a Python script to fetch and print the title of a webpage using the 'requests' and 'BeautifulSoup' libraries. Test it with the URL: 'https://example.com'.
import requests
from bs4 import BeautifulSoup

def get_webpage_title(url):

    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')

        title = soup.title.string if soup.title else 'No title found'
        return title
    else:
        return f'Error: {response.status_code}'

url = 'https://example.com'
title = get_webpage_title(url)
print(f'Title of the webpage: {title}')

