# -*- coding: utf-8 -*-
"""Day-15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ccCYFh7lls1ZwtpSkyYkhu3dxHggB6Tc
"""

#Write a Python function using regular expressions to extract all email addresses from a given string. Test it with the input: 'Contact us at support@example.com and sales@example.org.'

import re

def extract_emails(text):
    email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'

    emails = re.findall(email_pattern, text)

    return emails

# Test the function
input_text = 'Contact us at support@example.com and sales@example.org.'
emails = extract_emails(input_text)
print(emails)